### ISSUE TITLE
Link to documentation is broken 

### ISSUE THREAD

**Issue by Alksar** [chronicle-stack/Chronicle#19]
Link from Readme.MD is broken :

https://github.com/chronicle-stack/Chronicle/blob/master/chronicle.readthedocs.io

**Comment by GooRiOn** [comment]
solved, thx!

**Comment by GooRiOn** [comment]
or maybe not :D that's weird

**Comment by EduardoPires** [comment]
Not solved yet! Same error here.

**Comment by paolofulgoni** [comment]
@EduardoPires I think it's not broken, but the documentation is missing...
take a look here: https://github.com/chronicle-stack/Chronicle.Docs
it's just some sort of default content
