### ISSUE TITLE
More properties in ISagaContext 

### ISSUE THREAD

**Issue by Mikix123** [chronicle-stack/Chronicle#8]
Hi is it possible to add more properties in ISagaContext interface?

**Comment by GooRiOn** [comment]
What do you mean by more properties? I thought about adding some sort of metadata like ``IDictionary<string, string>`` to allow storing something as KV.

**Comment by george-weare8** [comment]
Is the IDictionary<string, string> still considered? That would be a good helper for additional metadata.

**Comment by GooRiOn** [comment]
There's `` IReadOnlyCollection<ISagaContextMetadata> Metadata { get; }`` available on ``ISagaContext``
